#ifndef CONFIG_H
#define CONFIG_H

#define MODEL_ID_SIZE 64
#define MINHASH_SIZE 256
#define RAGFILE_MAGIC 0x52414746 // "RAGF" in ASCII
#define RAGFILE_VERSION 1
#define METADATA_MAX_SIZE 1024


#endif // CONFIG_H
